//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class mhc_AutoImages
{
    public int Id { get; set; }
    public string AutoId { get; set; }
    public int mhc_AutosId { get; set; }
    public int mhc_Images_ImageId { get; set; }

    public virtual mhc_Images mhc_Images { get; set; }
    public virtual mhc_Autos mhc_Autos { get; set; }
}

public partial class mhc_Autos
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public mhc_Autos()
    {
        this.mhc_AutoImages = new HashSet<mhc_AutoImages>();
        this.mhc_Tasks = new HashSet<mhc_Tasks>();
        this.mhc_Likes = new HashSet<mhc_Likes>();
    }

    public int Id { get; set; }
    public string Make { get; set; }
    public string Model { get; set; }
    public string Year { get; set; }
    public string Cost { get; set; }
    public string RecordStatus { get; set; }
    public string UserId { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<mhc_AutoImages> mhc_AutoImages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<mhc_Tasks> mhc_Tasks { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<mhc_Likes> mhc_Likes { get; set; }
}

public partial class mhc_Images
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public mhc_Images()
    {
        this.mhc_AutoImages = new HashSet<mhc_AutoImages>();
        this.mhc_Likes = new HashSet<mhc_Likes>();
        this.mhc_TaskImages = new HashSet<mhc_TaskImages>();
    }

    public int ImageId { get; set; }
    public string ImageDescription { get; set; }
    public string Caption { get; set; }
    public string Path { get; set; }
    public string FileName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<mhc_AutoImages> mhc_AutoImages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<mhc_Likes> mhc_Likes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<mhc_TaskImages> mhc_TaskImages { get; set; }
}

public partial class mhc_ItemType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public mhc_ItemType()
    {
        this.mhc_Likes = new HashSet<mhc_Likes>();
    }

    public int Id { get; set; }
    public string TypeDesc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<mhc_Likes> mhc_Likes { get; set; }
}

public partial class mhc_Likes
{
    public int Id { get; set; }
    public string Item_id { get; set; }
    public string Item_type { get; set; }
    public string RecordStatus { get; set; }
    public string UserID { get; set; }
    public string AuditDateTime { get; set; }
    public string Liked { get; set; }
    public int mhc_ItemType_Id { get; set; }
    public int mhc_Images_ImageId { get; set; }
    public int mhc_Autos_Id { get; set; }

    public virtual mhc_Autos mhc_Autos { get; set; }
    public virtual mhc_Images mhc_Images { get; set; }
    public virtual mhc_ItemType mhc_ItemType { get; set; }
}

public partial class mhc_TaskImages
{
    public int Id { get; set; }
    public int TaskId { get; set; }
    public int mhc_TasksId { get; set; }
    public int mhc_Images_ImageId { get; set; }

    public virtual mhc_Images mhc_Images { get; set; }
    public virtual mhc_Tasks mhc_Tasks { get; set; }
}

public partial class mhc_Tasks
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public mhc_Tasks()
    {
        this.mhc_TaskImages = new HashSet<mhc_TaskImages>();
        this.mhc_Tasks2 = new HashSet<mhc_Tasks>();
    }

    public int AutoId { get; set; }
    public string TaskName { get; set; }
    public string TaskDescription { get; set; }
    public int ParentTaskId { get; set; }
    public string SortOrder { get; set; }
    public string HoursEstimate { get; set; }
    public string HoursActual { get; set; }
    public string CostEstimate { get; set; }
    public string CostActual { get; set; }
    public short TaskStatus { get; set; }
    public string RecordStatus { get; set; }
    public int TaskId { get; set; }
    public int mhc_AutosId { get; set; }

    public virtual mhc_Autos mhc_Autos { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<mhc_TaskImages> mhc_TaskImages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<mhc_Tasks> mhc_Tasks2 { get; set; }
    public virtual mhc_Tasks mhc_ParentTasks1 { get; set; }
}
