//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class MyHobbyCarEntities : DbContext
{
    public MyHobbyCarEntities()
        : base("name=MyHobbyCarEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<mhc_AutoImages> mhc_AutoImages { get; set; }
    public virtual DbSet<mhc_Autos> mhc_Autos { get; set; }
    public virtual DbSet<mhc_Images> mhc_Images { get; set; }
    public virtual DbSet<mhc_ItemType> mhc_ItemType { get; set; }
    public virtual DbSet<mhc_Likes> mhc_Likes { get; set; }
    public virtual DbSet<mhc_TaskImages> mhc_TaskImages { get; set; }
    public virtual DbSet<mhc_Tasks> mhc_Tasks { get; set; }
}
